<Project Sdk="Dalamud.CN.NET.Sdk/15.0.0">

    <PropertyGroup>
        <Title>EdgeTTS.Dalamud</Title>
        <Description>Leverage Microsoft Azure Neural Text-to-Speech to provide a more powerful and fluid text-to-speech service within Dalamud.</Description>
        <Authors>AtmoOmen</Authors>
        <Version>1.0.1.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\EdgeTTS\EdgeTTS.csproj"/>
        <ProjectReference Include="..\OmenTools\OmenTools.csproj"/>
        <None Include="Assets\Langs\*.json" CopyToOutputDirectory="Always"/>
        <None Include="Assets\icon.png" CopyToOutputDirectory="Always"/>
        <None Include="EdgeTTS.Dalamud.json"/>
    </ItemGroup>

</Project>
